swagger: "2.0"
info:
  version: 1.0.0
  title: ICASA API
  description: 
    A simple API to get formated information from the google docs ICASA standar
schemes:
  - https
#host: agrevent.com
#basePath: /icasa_api
host: localhost:4000
basePath: /icasa_api
paths:
  /cropcodes:
    get:
      summary: Gets some Crop information
      description: Returns a list containing all crops
      responses:
        200:
          description: A list of Crops
          schema:
            $ref: "#/definitions/CropList"
        500:
          $ref: "#/responses/Standard500ErrorResponse"
  /measures:
    get:
      summary: Gets some Measures information
      description: Returns a list containing all the ICASA measures
      responses:
        200:
          description: A list of measures names
          schema:
            $ref: "#/definitions/MeasuresList"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

  /measures/validator_names:
    post:
      summary: Validate user measures
      description: Returns a list containing all the user measures and the validation for each variable against icasa format
      responses:
        200:
          description: A list of measures names and validations
          schema:
            $ref: "#/definitions/MeasureValidationList"
        500:
          $ref: "#/responses/Standard500ErrorResponse"

definitions:
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: string
      message:
        type: string
  Crop:
    properties:
      crop_code:
        type: string
      common_name:
        type: string

  CropList:
    type: array
    items:
      $ref: "#/definitions/Crop"

  MeasuresList:
    type: array
    items:
      type: string

  MeasureValidationList:
    type: array
    items:
     properties:
      variable_name:
        type: string
      is_in:
        type: boolean

responses:
  Standard500ErrorResponse:
    description: An unexpected error occured.
    schema:
      $ref: "#/definitions/Error"
  PersonDoesNotExistResponse:
    description: Person does not exist.